services:
  deploy-dev:
    container_name: deploy-dev
    image: docker.io/spritelydev/dotnet10-devcontainer:0.4.13@sha256:4e1767e591bbbfceb81a8241686da1cb03ab72de8ad6f0ce66fb4e9362c5434f
    privileged: true
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
    # Environment variables have higher precedence than the .env file
    environment:
      - NUGET_TOKEN=${NUGET_TOKEN}
