services:
  deploy-dev:
    container_name: deploy-dev
    image: docker.io/spritelydev/dotnet10-devcontainer:0.4.61@sha256:dc644d6831f4a81ab0f9ce19fa1b604beb94cdfd0afcaf650d0b6279023ab89e
    privileged: true
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
    # Environment variables have higher precedence than the .env file
    environment:
      - NUGET_TOKEN=${NUGET_TOKEN}
