services:
  deploy-dev:
    container_name: deploy-dev
    image: docker.io/spritelydev/dotnet10-devcontainer:0.4.108@sha256:c29853e50a94f3a80ccc1447aa4ddc165d4db7137a7ebf0c4f72738c5990610d
    privileged: true
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
    # Environment variables have higher precedence than the .env file
    environment:
      - NUGET_TOKEN=${NUGET_TOKEN}
