name: Build

on: [push, workflow_dispatch]

permissions:
  contents: write # To be able to apply semantic version tags to the repository

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@0d840b974c0b9d8d51be1bc138a02c0107b29023 # v0.8.9

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@0d840b974c0b9d8d51be1bc138a02c0107b29023 # v0.8.9
        with:
          version: ${{ steps.version.outputs.version }}
