name: Build

on: [push, workflow_dispatch]

permissions:
  contents: write # To be able to apply semantic version tags to the repository

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@88c0c267d6333a93a9c96bfbe57a343163cd67ff # v0.8.1

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@88c0c267d6333a93a9c96bfbe57a343163cd67ff # v0.8.1
        with:
          version: ${{ steps.version.outputs.version }}
