name: Build

on: [push, workflow_dispatch]

permissions:
  contents: write # To be able to apply semantic version tags to the repository

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@008d0d757a133abcc1a391f3611acab202a5d3d9 # v0.7.8

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@008d0d757a133abcc1a391f3611acab202a5d3d9 # v0.7.8
        with:
          version: ${{ steps.version.outputs.version }}
