name: Renovate

on:
  workflow_dispatch:
    inputs:
      renovateVersion:
        description: The version of Renovate to use. Leave empty to use the latest version.
        required: false
        default: ''
      renovateLogLevel:
        description: The log level for Renovate.
        required: false
        default: info
        type: choice
        options:
          - trace
          - debug
          - info
          - warn
          - error
          - fatal

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Generate token
        id: renovate-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Renovate
        uses: renovatebot/github-action@79dc0ba74dc3de28db0a7aeb1d0b95d5bf5fde2a # v46.1.13
        with:
          token: ${{ steps.renovate-token.outputs.token }}
          renovate-version: ${{ inputs.renovateVersion }}
        env:
          LOG_LEVEL: ${{ inputs.renovateLogLevel }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: false
